# Generated by Django 5.2 on 2025-04-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedikura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('procedure_time', models.IntegerField()),
                ('descripton', models.TextField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pedikúra',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('descripton', models.TextField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Řasy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zdravi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('descripton', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Zdraví',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZdraviContacte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('descripton', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
