# Generated by Django 5.2 on 2025-04-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasy',
            name='procedure_time',
            field=models.IntegerField(default=0),
        ),
    ]
