# Generated by Django 5.2 on 2025-04-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_rasy_procedure_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZdraviContacte',
            new_name='Contacte',
        ),
    ]
