# Generated by Django 4.2.20 on 2025-05-05 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0002_update_health_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedikurareview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rasyreview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='zdravireview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pedikurareview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rasyreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zdravireview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zdravi',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pedikurareview',
            unique_together={('pedikura', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='rasyreview',
            unique_together={('rasy', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='zdravireview',
            unique_together={('zdravi', 'user')},
        ),
        migrations.RemoveField(
            model_name='pedikurareview',
            name='review',
        ),
        migrations.RemoveField(
            model_name='rasyreview',
            name='review',
        ),
        migrations.RemoveField(
            model_name='zdravireview',
            name='review',
        ),
    ]
