# Generated by Django 4.2.20 on 2025-05-06 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_order'),
        ('viewer', '0003_alter_pedikurareview_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(verbose_name='Datum zakázky')),
                ('description', models.TextField(blank=True, verbose_name='Popis zakázky')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Zakázka',
                'verbose_name_plural': 'Zakázky',
                'ordering': ['-service_date'],
            },
        ),
    ]
