# Generated by Django 5.2 on 2025-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_rename_zdravicontacte_contacte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacte',
            name='descripton',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='pedikura',
            name='descripton',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rasy',
            name='descripton',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='zdravi',
            name='descripton',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
