# Generated by Django 5.2 on 2025-04-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_contacte_descripton_alter_pedikura_descripton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacte',
        ),
        migrations.RenameField(
            model_name='pedikura',
            old_name='descripton',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='rasy',
            old_name='descripton',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='zdravi',
            old_name='descripton',
            new_name='description',
        ),
    ]
