# Generated by Django 4.2.20 on 2025-05-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='viewer.contact'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='Zobrazit na home stránce'),
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.BooleanField(default=False, verbose_name='Zobrazit na order strance'),
        ),
    ]
