# Generated by Django 5.2 on 2025-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_contact_delete_contacte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name_plural': 'Kontakt'},
        ),
        migrations.AddField(
            model_name='contact',
            name='ico',
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
