# Generated by Django 5.2 on 2025-04-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_contact_options_contact_ico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
