# Generated by Django 4.2.20 on 2025-05-16 09:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_contact_options_contactreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novinky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulek', models.CharField(max_length=200)),
                ('obsah', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('publikovano', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Novinka',
                'verbose_name_plural': 'Novinky',
                'ordering': ['-datum_vytvoreni'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='contact1',
            field=models.BooleanField(default=False, verbose_name='Zobrazit na stránce Kontakt'),
        ),
        migrations.AddField(
            model_name='image',
            name='pedikura1',
            field=models.BooleanField(default=False, verbose_name='Zobrazit na stránce Pedikura'),
        ),
        migrations.AddField(
            model_name='image',
            name='rasy1',
            field=models.BooleanField(default=False, verbose_name='Zobrazit na stránce Řasy'),
        ),
        migrations.AddField(
            model_name='image',
            name='zdravi1',
            field=models.BooleanField(default=False, verbose_name='Zobrazit na stránce Zdraví'),
        ),
        migrations.AddField(
            model_name='pedikura',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 16, 9, 32, 53, 50714, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedikura',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rasy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 16, 9, 33, 56, 461084, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rasy',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zdravi',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 16, 9, 34, 12, 976958, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zdravi',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
