# Generated by Django 4.2.20 on 2025-05-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_novinky_contact_created_contact_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novinky',
            name='image',
        ),
        migrations.RemoveField(
            model_name='novinky',
            name='publikovano',
        ),
        migrations.AddField(
            model_name='novinky',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='novinky/', verbose_name='Obrázek'),
        ),
    ]
