# Generated by Django 4.2.20 on 2025-05-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_remove_novinky_image_remove_novinky_publikovano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novinky',
            name='publikovano',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='novinky',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='novinky/'),
        ),
    ]
