# Generated by Django 4.2.20 on 2025-05-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_novinky_publikovano_alter_novinky_obrazek'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovinkyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='novinky_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novinka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='viewer.novinky')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
