# Generated by Django 4.2.20 on 2025-05-17 20:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0011_novinkyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactreview',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='contactreview',
            old_name='emaul',
            new_name='email',
        ),
        migrations.AlterUniqueTogether(
            name='contactreview',
            unique_together={('contact', 'user')},
        ),
    ]
