# Generated by Django 4.2.20 on 2025-05-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_alter_contactreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedikurareview',
            options={'ordering': ['-updated'], 'permissions': [('change_review', 'Může upravovat všechny recenze'), ('delete_review', 'Může mazat všechny recenze')]},
        ),
    ]
