# Generated by Django 4.2.20 on 2025-05-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_alter_pedikurareview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactreview',
            options={'ordering': ['-created'], 'permissions': [('change_review', 'Může upravovat všechny recenze'), ('delete_review', 'Může mazat všechny recenze')]},
        ),
        migrations.AlterModelOptions(
            name='rasyreview',
            options={'ordering': ['-updated'], 'permissions': [('change_review', 'Může upravovat všechny recenze'), ('delete_review', 'Může mazat všechny recenze')]},
        ),
        migrations.AlterModelOptions(
            name='zdravireview',
            options={'ordering': ['-updated'], 'permissions': [('change_review', 'Může upravovat všechny recenze'), ('delete_review', 'Může mazat všechny recenze')]},
        ),
    ]
