# Generated by Django 4.2.20 on 2025-05-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_alter_contactreview_options_alter_rasyreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactreview',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='pedikurareview',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='rasyreview',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='zdravireview',
            options={'ordering': ['-updated']},
        ),
    ]
