# Generated by Django 5.2.15 on 2026-06-26 18:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novinky',
            name='obsah',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Obsah'),
        ),
        migrations.AlterField(
            model_name='pedikura',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='zdravi',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Popis'),
        ),
    ]
